"""Convert the editable P3 Netpbm ground tile into checked-in N64 RGBA5551 data.

Normal builds include the generated header and do not run this converter.
"""
import argparse
from pathlib import Path


def convert(source):
    tokens = ' '.join(line.split('#', 1)[0] for line in source.splitlines()).split()
    if tokens[:4] != ['P3', '16', '16', '255']:
        raise ValueError('expected an ASCII P3 RGB image, exactly 16x16 with maximum 255')
    try:
        channels = [int(value) for value in tokens[4:]]
    except ValueError as error:
        raise ValueError('pixel channels must be integers in 0..255') from error
    if len(channels) != 16 * 16 * 3 or any(value < 0 or value > 255 for value in channels):
        raise ValueError('expected exactly 256 RGB pixels with channel values in 0..255')
    pixels = [((channels[i] >> 3) << 11) | ((channels[i + 1] >> 3) << 6) |
              ((channels[i + 2] >> 3) << 1) | 1 for i in range(0, len(channels), 3)]
    rows = [', '.join(f'0x{pixel:04x}' for pixel in pixels[i:i + 16]) for i in range(0, 256, 16)]
    return ('/* Generated by scripts/make-texture.py from assets/textures/ground.ppm. */\n'
            '/* Original 16x16 RGB tile; opaque RGBA5551, 512 bytes, big-endian on N64. */\n'
            'static const uint16_t ground_texture_pixels[256] __attribute__((aligned(8))) = {\n' +
            ''.join(f'    {row},\n' for row in rows) + '};\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=Path('assets/textures/ground.ppm'))
    parser.add_argument('--output', type=Path, default=Path('src/generated/ground_texture.h'))
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        result = convert(args.source.read_text())
        if args.check:
            if args.output.read_text() != result:
                parser.error('generated ground texture is stale; run python3 scripts/make-texture.py')
        else:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(result)
    except ValueError as error:
        parser.error(str(error))


if __name__ == '__main__':
    main()
