"""Rebuild the editable Blender rabbit and the ROM's integer mesh.

Run: blender --background --python scripts/make-rabbit.py
No Blender installation is needed for normal ROM builds.
"""
import bpy
import math
from pathlib import Path
from mathutils import Vector

ROOT = Path(__file__).resolve().parents[1]
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)

COLORS = [(247, 237, 214), (233, 143, 159), (38, 48, 63), (234, 123, 83), (255, 250, 230)]
materials = []
for name, rgb in zip(['Vanilla fur', 'Rose ears and nose', 'Espresso eyes', 'Player jersey', 'Cream muzzle'], COLORS):
    mat = bpy.data.materials.new(name)
    mat.diffuse_color = (*[c / 255 for c in rgb], 1)
    mat.use_nodes = True
    mat.node_tree.nodes["Principled BSDF"].inputs["Base Color"].default_value = mat.diffuse_color
    mat.node_tree.nodes["Principled BSDF"].inputs["Roughness"].default_value = .82
    materials.append(mat)

parts = []
def orb(name, location, scale, material=0, segments=6, rings=3, part=0, tilt=0):
    if rings == 2:
        # Blender clamps UV-sphere rings to three. An explicit octahedron keeps
        # small limbs and facial details at eight triangles on the N64.
        mesh = bpy.data.meshes.new(name)
        mesh.from_pydata([(1,0,0),(0,1,0),(-1,0,0),(0,-1,0),(0,0,1),(0,0,-1)], [],
                        [(4,0,1),(4,1,2),(4,2,3),(4,3,0),(5,1,0),(5,2,1),(5,3,2),(5,0,3)])
        mesh.update()
        obj = bpy.data.objects.new(name, mesh)
        bpy.context.collection.objects.link(obj)
        obj.location = location
    else:
        bpy.ops.mesh.primitive_uv_sphere_add(segments=segments, ring_count=rings, radius=1, location=location)
        obj = bpy.context.object
    obj.name = name
    obj.scale = scale
    obj.rotation_euler[1] = tilt
    obj.data.materials.append(materials[material])
    obj['animation_part'] = part
    parts.append(obj)
    return obj

orb('Pear-shaped jersey', (0, 0, 0.97), (.44, .31, .57), 3)
orb('Big soft head', (0, -.035, 1.70), (.49, .39, .43), rings=4)
for side in [-1, 1]:
    orb('Long ear', (side*.235, .015, 2.28), (.145, .115, .60), segments=4, rings=2, part=3, tilt=side*.12)
    orb('Pink inner ear', (side*.235, -.094, 2.30), (.082, .021, .43), 1, segments=4, rings=2, part=3, tilt=side*.12)
    orb('Little arm', (side*.47, -.015, .99), (.145, .17, .37), segments=6, rings=2, part=1 if side < 0 else 2, tilt=side*.22)
    orb('Large bunny shoe', (side*.245, -.12, .23), (.22, .34, .23), segments=6, rings=2, part=2 if side < 0 else 1)
    orb('Bright eye', (side*.19, -.383, 1.77), (.061, .029, .095), 2, segments=4, rings=2)
    orb('Eye sparkle', (side*.19-.012, -.412, 1.809), (.020, .010, .025), 4, segments=4, rings=2)
    orb('Muzzle cheek', (side*.10, -.381, 1.57), (.135, .068, .10), 4, segments=4, rings=2)
orb('Tiny nose', (0, -.465, 1.64), (.050, .032, .042), 1, segments=4, rings=2)
orb('Cotton tail', (0, .35, .72), (.21, .19, .21), 4, segments=4, rings=2)

bpy.context.view_layer.update()
vertices, faces = [], []
light = Vector((-.35, -.6, .8)).normalized()
for obj in parts:
    base = len(vertices)
    for v in obj.data.vertices:
        p = obj.matrix_world @ v.co
        vertices.append((round(p.x*256), round(p.z*256), round(-p.y*256), obj['animation_part']))
    obj.data.calc_loop_triangles()
    normal_matrix = obj.matrix_world.to_3x3().inverted().transposed()
    for tri in obj.data.loop_triangles:
        normal = (normal_matrix @ tri.normal).normalized()
        shade = round(255 * (.64 + .36 * max(0, normal.dot(light))))
        material = materials.index(obj.data.materials[0])
        faces.append((*[base+i for i in tri.vertices], material, shade))

output = ROOT / 'src/generated/rabbit.zig'
output.parent.mkdir(parents=True, exist_ok=True)
with output.open('w') as f:
    f.write('// Generated by Blender via scripts/make-rabbit.py. Units: 1/256 metre.\n')
    f.write('pub const Vertex = struct { x: i16, y: i16, z: i16, part: u8 };\n')
    f.write('pub const Face = struct { a: u16, b: u16, c: u16, material: u8, shade: u8 };\n')
    f.write('pub const vertices = [_]Vertex{\n')
    for x,y,z,p in vertices:
        f.write(f'    .{{ .x = {x}, .y = {y}, .z = {z}, .part = {p} }},\n')
    f.write('};\npub const faces = [_]Face{\n')
    for a,b,c,m,s in faces:
        f.write(f'    .{{ .a = {a}, .b = {b}, .c = {c}, .material = {m}, .shade = {s} }},\n')
    f.write('};\n')

# A small studio scene stays in the .blend for easy editing and asset review.
bpy.ops.mesh.primitive_plane_add(size=200)
floor = bpy.context.object
floor.name = 'Preview floor (not exported)'
mat = bpy.data.materials.new('Sage backdrop')
mat.diffuse_color = (.25, .37, .32, 1)
mat.use_nodes = True
mat.node_tree.nodes['Principled BSDF'].inputs['Base Color'].default_value = mat.diffuse_color
floor.data.materials.append(mat)
bpy.ops.object.camera_add(location=(4, -7, 3.8))
camera = bpy.context.object
camera.rotation_euler = (Vector((0, 0, 1.35)) - camera.location).to_track_quat('-Z', 'Y').to_euler()
camera.data.type = 'ORTHO'
camera.data.ortho_scale = 3.7
bpy.context.scene.camera = camera
bpy.ops.object.light_add(type='AREA', location=(-3, -4, 7))
bpy.context.object.data.energy = 450
bpy.context.object.data.shape = 'DISK'
bpy.context.object.data.size = 5
scene = bpy.context.scene
scene.render.engine = 'CYCLES'
scene.cycles.samples = 24
scene.render.resolution_x = 640
scene.render.resolution_y = 640
scene.render.resolution_percentage = 100
scene.world.color = (.35, .35, .35)
scene.render.filepath = str(ROOT / 'assets/rabbit-preview.png')
bpy.ops.wm.save_as_mainfile(filepath=str(ROOT / 'assets/rabbit.blend'))
bpy.ops.render.render(write_still=True)
print(f'Exported {len(vertices)} vertices / {len(faces)} triangles to {output}')
