# Convert the editable P3 tile to checked-in opaque N64 RGBA5551 pixels.
export def convert [source: string] {
    let tokens = ($source | lines | each { split row '#' | first } | str join ' ' | split row --regex '\s+' | where $it != '')
    if ($tokens | first 4) != ['P3' '16' '16' '255'] {
        error make {msg: 'expected an ASCII P3 RGB image, exactly 16x16 with maximum 255'}
    }
    let values = ($tokens | skip 4)
    if ($values | any { $in !~ '^[+-]?\d+$' }) {
        error make {msg: 'pixel channels must be integers in 0..255'}
    }
    let channels = ($values | into int)
    if ($channels | length) != 768 or ($channels | any { $in < 0 or $in > 255 }) {
        error make {msg: 'expected exactly 256 RGB pixels with channel values in 0..255'}
    }
    let pixels = ($channels | chunks 3 | each {|rgb|
        let pixel = ((($rgb.0 | bits shr 3) | bits shl 11) + (($rgb.1 | bits shr 3) | bits shl 6) + (($rgb.2 | bits shr 3) | bits shl 1) + 1)
        '0x' + ($pixel | into binary --endian big | bytes at 6.. | encode hex | str lowercase)
    })
    let rows = ($pixels | chunks 16 | each {|row| '    ' + ($row | str join ', ') + ",\n" } | str join)
    ("/* Generated by scripts/make-texture.nu from assets/textures/ground.ppm. */\n" +
    "/* Original 16x16 RGB tile; opaque RGBA5551, 512 bytes, big-endian on N64. */\n" +
    "static const uint16_t ground_texture_pixels[256] __attribute__((aligned(8))) = {\n" + $rows + "};\n")
}

export def main [
    --source: path = 'assets/textures/ground.ppm'
    --output: path = 'src/generated/ground_texture.h'
    --check
] {
    let result = (convert (open --raw $source))
    if $check {
        if (open --raw $output) != $result {
            error make {msg: 'generated ground texture is stale; run nu scripts/make-texture.nu'}
        }
    } else {
        mkdir ($output | path dirname)
        let temporary = ($output | path dirname | path join $'.texture-(random uuid).tmp')
        $result | save --raw $temporary
        mv --force $temporary $output
    }
}
