"""Blender-independent validation and serialization of the template mesh format."""
import math


class MeshError(ValueError):
    """An asset error suitable for showing directly to its author."""


def integer(value, low, high, label):
    if type(value) is not int or not low <= value <= high:
        raise MeshError(f"{label}: expected an integer in {low}..{high}, got {value!r}")
    return value


def quantize_position(position, label):
    """World-space Blender X/Z/-Y to signed Q8 game X/Y/Z."""
    if len(position) != 3 or not all(math.isfinite(v) for v in position):
        raise MeshError(f"{label}: position must have three finite coordinates")
    result = tuple(round(v * 256) for v in (position[0], position[2], -position[1]))
    for axis, value in zip("xyz", result):
        integer(value, -32768, 32767, f"{label} {axis} after Q8 conversion (check scale)")
    return result


def packed_vertex_count(vertices, faces):
    """Count the renderer's 64-vertex batches, including the 16-triangle shadow.

    Source identity/material/shade determine sharing. Padding each batch to an
    even size is required by Tiny3D's paired vertex DMA format.
    """
    triangles = [(tuple(face[:3]), face[3], face[4]) for face in faces]
    shadow = len(vertices)
    triangles += [((shadow, shadow + 1 + i, shadow + 1 + (i + 1) % 16), -1, 255)
                  for i in range(16)]
    total, batches, keys = 0, 0, set()
    for ids, material, shade in triangles:
        if not keys or len(keys) > 61:
            total += len(keys) + len(keys) % 2
            keys = set()
            batches += 1
        keys.update((index, material, shade) for index in ids)
    return total + len(keys) + len(keys) % 2, batches


def validate_mesh(vertices, faces, colors):
    if not vertices or not faces:
        raise MeshError("export selection contains no mesh triangles")
    if not 1 <= len(colors) <= 255:
        raise MeshError("palette must contain 1..255 colors (one slot is reserved for the shadow)")
    for i, color in enumerate(colors):
        integer(color, 0, 0xffffffff, f"palette color {i}")
    if len(vertices) + 17 > 65535:
        raise MeshError("source vertex count plus shadow exceeds u16 indices; simplify the mesh")
    for i, vertex in enumerate(vertices):
        if len(vertex) != 4:
            raise MeshError(f"vertex {i}: expected x, y, z and animation_part")
        for axis, value in zip("xyz", vertex[:3]):
            integer(value, -32768, 32767, f"vertex {i} {axis}")
        integer(vertex[3], 0, 3, f"vertex {i} animation_part (0=body, 1/2=opposing limbs, 3=sway)")
        # Reserve room for the sample world's translation, rotation, gait and hop.
        # Game forks that enlarge this envelope must update both runtime and check.
        if abs(vertex[0]) + abs(vertex[2]) + 46 + 13 * 256 > 32767:
            raise MeshError(f"vertex {i}: horizontal extent can overflow during rotation/movement; reduce scale")
        if vertex[1] < 0 or vertex[1] + 14 + 570 > 32767:
            raise MeshError(f"vertex {i}: height must be above the ground and leave room for bob/hop; adjust origin/scale")
    for i, face in enumerate(faces):
        if len(face) != 5:
            raise MeshError(f"triangle {i}: expected three indices, palette index and shade")
        for index in face[:3]:
            integer(index, 0, len(vertices) - 1, f"triangle {i} vertex index")
        integer(face[3], 0, len(colors) - 1, f"triangle {i} material index")
        integer(face[4], 0, 255, f"triangle {i} shade")
        a, b, c = (vertices[index][:3] for index in face[:3])
        ab = tuple(y - x for x, y in zip(a, b))
        ac = tuple(y - x for x, y in zip(a, c))
        cross = (ab[1] * ac[2] - ab[2] * ac[1],
                 ab[2] * ac[0] - ab[0] * ac[2],
                 ab[0] * ac[1] - ab[1] * ac[0])
        if cross == (0, 0, 0):
            raise MeshError(f"triangle {i}: degenerate after Q8 conversion; remove it or increase detail size")
    if (len(faces) + 16) * 3 > 4096:
        raise MeshError("triangle count plus contact shadow exceeds the 4096-index mesh capacity")
    count, batches = packed_vertex_count(vertices, faces)
    if count > 768 or batches > 64:
        raise MeshError(f"mesh needs {count}/768 animated vertices and {batches}/64 batches including shadow; simplify geometry or reduce shade splits")
    return count, batches


def serialize_mesh(vertices, faces, colors):
    count, _ = validate_mesh(vertices, faces, colors)
    lines = ["// Generated by scripts/export-mesh.py. Units: 1/256 metre.",
             "pub const Vertex = struct { x: i16, y: i16, z: i16, part: u8 };",
             "pub const Face = struct { a: u16, b: u16, c: u16, material: u8, shade: u8 };",
             f"pub const packed_vertex_count = {count};",
             "pub const colors = [_]u32{ " + ", ".join(f"0x{color:08x}" for color in colors) + " };",
             "pub const vertices = [_]Vertex{"]
    lines += [f"    .{{ .x = {x}, .y = {y}, .z = {z}, .part = {part} }},"
              for x, y, z, part in vertices]
    lines += ["};", "pub const faces = [_]Face{"]
    lines += [f"    .{{ .a = {a}, .b = {b}, .c = {c}, .material = {material}, .shade = {shade} }},"
              for a, b, c, material, shade in faces]
    return "\n".join(lines + ["};", ""])
